### ISSUE TITLE
add support for passing references `jsonnet`/`json` files via the `--iqldata` arg

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-exec#10]
For example, running the following action in a workflow: 

```yaml
      - name: Run exec with a vars file
        uses: stackql/stackql-exec@v1.0.0
        with:
          auth_obj_path: './stackql_scripts/auth.json'
          query_file_path: './stackql_scripts/google-example.iql'
          data: ./stackql_scripts/vars.jsonnet
```
would run the command

```
stackql exec --auth="${AUTH}" -i ./stackql_scripts/google-example.iql --iqldata ./stackql_scripts/vars.jsonnet
```
This would render a templated query with the variables from the `jsonnet` file
